version: "3"
services:
  db:
    image: mysql:5.7.7
    container_name: camaleon_db
    volumes:
      - './data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: mypass
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    container_name: webapp
    environment:
      RAILS_ENV: production
      VIRTUAL_HOST: blockchain.paynelabs.net #change to meet your needs
      DB_MYSQL_ROOT_PASSWORD: mypass #change for production safety
      DB_MYSQL_HOST: db
      DB_DATABASE_NAME: blockathondb
      LETSENCRYPT_HOST: blockchain.paynelabs.net
      LETSENCRYPT_EMAIL: blockchain.paynelabs.net
    links:
      - db
    volumes:
      - ./log:/usr/camaleon/log:rw

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
  outside:
    external:
      name: ${SERVICE_NETWORK:-webservices}